Create vm
bluebosh/bosh-linux-stemcell-builder pull request #1
Opened 2019-03-21 02:31 UTC by LiYa-Xu

2019-03-21 02:35 UTC, LiYa-Xu commented
Add a new job in building stemcell pipeline to OS reload an existing VM with the newly created SL community stemcell.

2019-03-21 03:29 UTC, mattcui requested changes
Make sure to pass shell check for all shell scripts.

2019-03-21 03:29 UTC, mattcui commented on ci/softlayer/tasks/deploy-vm.sh
> +curl -X POST -d '{"parameters":[ "FORCE",  { "imageTemplateId": "$image_id" }] }'https://$SL_USERNAME:$SL_API_KEY@api.softlayer.com/rest/v3/SoftLayer_Virtual_Guest/74649319/reloadOperatingSystem.json
Should not hardcode vm id, and don't expose vm id in public.

2019-03-23 04:35 UTC, mattcui reviewed
@LiYa-Xu  Please respond and mark resolve for each my comment, thanks

2019-03-23 04:35 UTC, mattcui commented on ci/softlayer/tasks/deploy-vm.sh
> +set -e -x -u
`set -o errexit -o nounset -o pipefail`

2019-03-23 04:35 UTC, mattcui commented on ci/softlayer/tasks/deploy-vm.yml
> +  SL_TOKEN:              required
should be `SL_API_KEY`??

2019-03-23 04:35 UTC, mattcui commented on ci/softlayer/tasks/deploy-vm.sh
> +curl -X POST -d '{"parameters":[ "FORCE",  { "imageTemplateId": "$image_id" }] }'https://$SL_USERNAME:$SL_API_KEY@api.softlayer.com/rest/v3/SoftLayer_Virtual_Guest/74649319/reloadOperatingSystem.json
need result check

2019-03-28 07:39 UTC, edwardstudy commented
@mattcui @LiYa-Xu Could we merge this PR?

2019-03-28 07:42 UTC, edwardstudy commented on ci/softlayer/tasks/deploy-vm.sh
> +
Could we follow other scripts and add `sed -e` to each script?

2019-03-28 07:56 UTC, merged